version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: chat-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - '3000:3000'
    networks:
      - chat-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://backend:3000/api/messages',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: chat-frontend
    restart: unless-stopped
    ports:
      - '4200:4200'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
